# Generated by Django 3.0.6 on 2021-12-10 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bestReads', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookplan',
            old_name='book_id',
            new_name='book',
        ),
        migrations.RenameField(
            model_name='bookplan',
            old_name='day_name_id',
            new_name='day_name',
        ),
        migrations.RenameField(
            model_name='bookplan',
            old_name='plan_id',
            new_name='plan',
        ),
    ]
