# Generated by Django 3.0.6 on 2021-12-13 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bestReads', '0002_auto_20211210_1712'),
    ]

    operations = [
        migrations.CreateModel(
            name='Votes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('votes', models.CharField(max_length=6)),
            ],
        ),
    ]
