# Generated by Django 3.0.6 on 2021-12-13 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bestReads', '0003_votes'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='votes',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bestReads.Votes'),
        ),
        migrations.AddField(
            model_name='plan',
            name='votes',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bestReads.Votes'),
        ),
        migrations.AlterField(
            model_name='votes',
            name='votes',
            field=models.CharField(max_length=6, null=True),
        ),
    ]
