# Generated by Django 3.0.6 on 2021-12-13 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bestReads', '0004_auto_20211213_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='votes',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='bestReads.Votes'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='votes',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='bestReads.Votes'),
        ),
    ]
