# Generated by Django 3.0.6 on 2021-12-13 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bestReads', '0005_auto_20211213_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='votes',
            name='votes',
            field=models.CharField(max_length=12, null=True),
        ),
    ]
